(require 'package)

(eval-when-compile
  (package-initialize)
  (unless (package-installed-p 'use-package)
    (package-refresh-contents)
    (package-install 'use-package))
  (require 'use-package)
  (setq use-package-always-defer t
        use-package-verbose t))

(package-refresh-contents)

(package-install 'aggressive-indent)
(package-install 'cape)
(package-install 'cider)
(package-install 'clj-refactor)
(package-install 'clojure-deps-new)
(package-install 'clojure-mode)
(package-install 'command-log-mode)
(package-install 'commify)
(package-install 'consult)
(package-install 'consult-eglot)
(package-install 'consult-org-roam)
(package-install 'consult-yasnippet)
(package-install 'corfu)
(package-install 'corfu-popupinfo)
(package-install 'corfu-terminal)
(package-install 'csv-mode)
(package-install 'daemons)
(package-install 'display-line-numbers)
;; (package-install 'ediff)
;; (package-install 'eglot)
(package-install 'embark)
(package-install 'embark-consult)
(package-install 'emojify)
(package-install 'ess)
(package-install 'flymake)
(package-install 'git-auto-commit-mode)
(package-install 'helpful)
(package-install 'highlight-indent-guides)
(package-install 'magit)
(package-install 'marginalia)
(package-install 'markdown-mode)
(package-install 'meow)
(package-install 'modus-themes)
(package-install 'neil)
(package-install 'orderless)
;; (package-install 'org)
(package-install 'org-appear)
(package-install 'org-cliplink)
(package-install 'org-modern)
(package-install 'org-protocol)
(package-install 'org-protocol)
(package-install 'org-roam)
(package-install 'org-roam-dailies) ;; Ensure the keymap is available
(package-install 'orgit)
(package-install 'paredit)
(package-install 'pass)
(package-install 'password-store)
(package-install 'pdf-tools)
(package-install 'pocket-reader)
(package-install 'popon)
(package-install 'rainbow-delimiters)
(package-install 'rainbow-mode)
(package-install 'separedit)
(package-install 'vertico)
(package-install 'vundo)
(package-install 'which-key)
(package-install 'windmove)
(package-install 'winner)
(package-install 'yasnippet)


(package-install 'consult-org-roam)
(package-install 'elfeed)
(package-install 'mastodon)
;; (package-install 'org)
(package-install 'org-modern)
(package-install 'org-roam)
(package-install 'org-transclusion)
